{% set name = "rfc3987" %}
{% set version = "1.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3c4d257a560d544e9826b38bc81db676890c79ab9d7ac92b39c7a253d5ca733

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - rfc3987

about:
  home: http://pypi.python.org/pypi/rfc3987
  license: GNU GPL3
  license_family: GPL3
  license_file: COPYING.txt
  summary: Parsing and validation of URIs (RFC 3986) and IRIs (RFC 3987)
  description: This module provides regular expressions according to RFC 3986 and RFC 3987
  dev_url: http://pypi.python.org/pypi/rfc3987

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
